### ISSUE TITLE
recon:proc_count does not take self() into account

### ISSUE THREAD

**Issue by define-null** [ferd/recon#22]
I faced with strange behaviour on one of the servers, when one of the metrics, which reported max message queue length started to report rather big increasing value. After some digging I found that somebody subscribed to the producer from the shell (console was attached to the process) and recon did not show it after calling recon:proc_count(message_queue_len,5) which confused a lot. While I don't think that attach is a good method to investigate on what is going on(in case remsh is used we can find out the violator with recon:proc_count/2), maybe it's better to include self() it in the search?

**Comment by ferd** [comment]
The reason I always removed `self()` from the search is that on any count that has to do with reductions or memory, it is not infrequent to see the shell be super high in the result (because it *is* actively counting everything), especially with the time-limited functions.

Because of that, and because you should likely *not* have a shell connected to a production node 24/7 (start Erlang in a daemon node with a name and connect to it when you need to), I thought the shell process should not show up in the results.

I'm not exactly sure I understand what your use case is and am not convinced there is a need to fix things. Can you explain more clearly what you mean by "somebody subscribed to the producer from the shell"? Do you mean that something produces a lot of messages and the shell was directly connected to it?

**Comment by define-null** [comment]
> Do you mean that something produces a lot of messages and the shell was directly connected to it?
yes, exactly. 

> Because of that, and because you should likely not have a shell connected to a production node 24/7 (start Erlang in a daemon node with a name and connect to it when you need to), I thought the shell process should not show up in the results.
Fully agree with you, I just described the use case, which happened because of some work needed at maintenance hours. Using attach is a bad habit in case of prod environment.

> The reason I always removed self() from the search is that on any count that has to do with reductions or memory, it is not infrequent to see the shell be super high in the result (because it is actively counting everything), especially with the time-limited functions.
makes sense, maybe it's better to clarify the documentation?

"Fetches a given attribute from all processes **except self()** and returns the biggest Num consumers."

**Comment by ferd** [comment]
Yeah I'll do that.

**Comment by ferd** [comment]
https://github.com/ferd/recon/commit/f6875ff8fb63205d41c719dc1fc67e1f915a3719 this commit contains it. I'm not releasing 2.2.2 yet because this is a 100% doc fix though.

**Comment by define-null** [comment]
Thank you)
