### ISSUE TITLE
Problem using recon_trace in Elixir

### ISSUE THREAD

**Issue by fremontmj** [ferd/recon#24]
In IEx I can trace using the following expression:

:recon_trace.calls({Server, :json_encode, 1}, 10)

When I attempt to get return values, I try (among many variants!):

:recon_trace.calls({Server, :json_encode, fn x -> return_trace end}, 10)

... and I get this fun message:                

Error: Unknown error code {122,'Elixir.IEx.Helpers',return_trace}
** (CaseClauseError) no case clause matching: {:error, :transform_error}
    (recon) src/recon_trace.erl:435: :recon_trace.validate_tspec/3
    (recon) src/recon_trace.erl:379: :recon_trace."-trace_calls/3-lc$^0/1-0-"/2
    (recon) src/recon_trace.erl:378: :recon_trace.trace_calls/3

Am I doing something wrong?  Or is this a problem in recon?  Or Elixir?

Thanks for this great package!

Best,

Mike

**Comment by ferd** [comment]
No idea. I have never used Elixir. I'm using [`dbg:fun2ms/1`](http://www.erlang.org/doc/man/dbg.html#fun2ms-1) to do the compiling of funs to match expressions. I have no idea what Elixir does with it or how to make it work with it.

**Comment by ferd** [comment]
Actually I re-checked and I stole code from `dbg`: https://github.com/ferd/recon/blob/master/src/recon_trace.erl#L565-L580
```erlang
fun_to_ms(ShellFun) when is_function(ShellFun) ->
    case erl_eval:fun_data(ShellFun) of
        {fun_data,ImportList,Clauses} ->
            case ms_transform:transform_from_shell(
                   dbg,Clauses,ImportList) of
                {error,[{_,[{_,_,Code}|_]}|_],_} ->
                    io:format("Error: ~s~n",
                              [ms_transform:format_error(Code)]),
                    {error,transform_error};
                Else ->
                    Else
            end;
        false ->
            exit(shell_funs_only)
    end. 
```

The fun passed in has to be evaluable by Erlang's stuff.

**Comment by fremontmj** [comment]
Thanks for looking into it!

Best,

Mike

**Comment by tatsuya6502** [comment]
I have some Erlang background and recently started to play with Elixir. I am writing Elixir wrapper modules for Recon modules, so that we can use recon_trace etc. from IEx.

If you are interested, please give them a try. I got wrappers for all Recon modules: recon, recon_alloc, recon_lib and recon_trace.

- https://github.com/tatsuya6502/recon_ex

Here is an example session; you will get return values and also get trace prints in Elixir's term format.

```iex
% cd recon_ex
% iex -S mix
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> ReconTrace.calls({:gb_trees, :_, fn(_) -> :return end}, 20, [scope: :local])
50
iex(2)> :gb_trees.enter(:key, "value", :gb_trees.empty)
01:29:05.865959 <0.117.0> :gb_trees.empty()
{1, {:key, "value", nil, nil}}
01:29:05.880923 <0.117.0> :gb_trees.empty/0 --> {0, nil}
01:29:05.881272 <0.117.0> :gb_trees.enter(:key, "value", {0, nil})
01:29:05.881644 <0.117.0> :gb_trees.is_defined(:key, {0, nil})
01:29:05.881945 <0.117.0> :gb_trees.is_defined_1(:key, nil)
01:29:05.882177 <0.117.0> :gb_trees.is_defined_1/2 --> false
01:29:05.882419 <0.117.0> :gb_trees.is_defined/2 --> false
01:29:05.882641 <0.117.0> :gb_trees.insert(:key, "value", {0, nil})
01:29:05.882921 <0.117.0> :gb_trees.insert_1(:key, "value", nil, 1)
01:29:05.883162 <0.117.0> :gb_trees.insert_1/4 --> {:key, "value", nil, nil}
01:29:05.883425 <0.117.0> :gb_trees.insert/3 --> {1, {:key, "value", nil, nil}}
01:29:05.883692 <0.117.0> :gb_trees.enter/3 --> {1, {:key, "value", nil, nil}}
iex(3)>
```

**Comment by tatsuya6502** [comment]
@ferd -

I think you can mark this issue as wontfix and close. Please redirect Elixir users to my project.

Anyway, thanks a lot for the great stuff!

**Comment by ferd** [comment]
That sounds fair to me.

**Comment by steele232** [comment]
Hi. Just wanted to add a useful note for those finding this later:

I encountered the same error while while trying to use the recon library from iex. I have a little bit of a mixed erlang and elixir background so I was looking at the erlang examples as a reference and trying to use recon trace like this: (a little goofy in hindsight)

```
:recon_trace.calls({'My.Server','_','_'},10)
```
But it failed with a very similar error as the OP had here.

The fix was to do atoms in the Elixir way:
```
:recon_trace.calls({RP.Server, :_, :_}, 10)
```
Then when I interacted with my GenServer, I was able to see the traces. 

This is just a comment and the issue can be closed again.
