### ISSUE TITLE
recon:rpc/3 badfun 

### ISSUE THREAD

**Issue by zhongwencool** [ferd/recon#31]
hi fred,
1. NodeA, NodeB are connected;
2. In NodeA I can do 

> rpc:call(NodeB, make, all, [[load]]).
> update_to_date

the problem is ：
>rpc:call(NodeB, erlang, apply, [fun() -> make:all([load]) end,[]]).

>{badrpc,{'EXIT',{{badfun,#Fun<shell.5.68187095>},
                 [{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,659}]},
                  {rpc,'-handle_call_call/6-fun-0-',5,
                       [{file,"rpc.erl"},{line,205}]}]}}}

they both compile their code from the same source ,but the machine system setting is different.

So:

Maybe change recon:rpc(Node, Fun, Timeout) to   recon:rpc(Node, M, F, A, Timeout) will be better?

**Comment by pichi** [comment]
This kind of error is typical for case of attemping to call fun made in module which exact version is not accesible on target node. In your case it can be different (exact) version of erl_eval or NodeB is in enbeded mode and erl_eval is not loaded.

**Comment by ferd** [comment]
@pichi is right. This error will happen whenever such a call is made with different versions of `erl_eval` for funs defined in the shell, or for modules themselves (maybe it's not there at all) for direct references like `fun M:A/Arity`.

If you want the `recon:rpc(Node, M, F, A, Timeout)` form I encourage you to use `rpc:call(Node, Module, Function, Args, Timeout)` -- I didn't put it into `recon` because it's already included in the libraries shipping with Erlang.

**Comment by zhongwencool** [comment]
But why it's work when I use rpc:call(Nodes,M,F,A)?
My version is 
NodeA：Erlang/OTP 17 [erts-6.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

NodeB:Erlang/OTP 17 [erts-6.3] [source [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

smp ?

**Comment by ferd** [comment]
You have two versions of OTP-17 that differ (erts-6.1 and erts-6.3) -- this likely means the `erl_eval` module has varying versions, and functions declared in the shell are attached to that module. This means it wouldn't work well unless you were making sure to load the same `erl_eval` module everywhere.

**Comment by zhongwencool** [comment]
got it , thanks~
