### ISSUE TITLE
recon_trace:calls for remote node

### ISSUE THREAD

**Issue by mmooyyii** [ferd/recon#81]
add function like this 
`
(a@127.0.0.1) >  recon_trace:remote_calls(['b@127.0.0.1','c@127.0.0.1'],{lists,seq,'_'},10).
`
`
(b@127.0.0.1) > lists:seq(1).
`
`
(c@127.0.0.1) > lists:seq(1).
`
all stdout will redirect to a@127.0.0.1
```
b@127.0.0.1 18:38:01.195994 <0.88.0>  lists:seq(1)  
c@127.0.0.1 18:38:01.195994 <0.89.0>  lists:seq(1)
```
It will work when debugging code in production consumer mode.
If you accept this issue,I will pull requests.

**Comment by ferd** [comment]
I'm afraid this is going to be tricky to make production-safe given the high volume of traces potentially run.
The counter approach works well locally because we have the ability to do backpressure handling like that. In a distributed setting the backpressure mechanism has to be a bit more sensitive to the distributed ports, and that requires doing things a bit more from scratch. Especially if the counter is local, you might kill remote nodes before yours even know there's a problem.

I would be tempted to say no to  this feature just because it's very hard to make it work safely.
